apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-credentials
type: Opaque
data:
  user: YnJpYW4=
  password: cGFzc3dvcmQx

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-auth-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres-auth-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-auth-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres-auth-pv

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: postgres-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth-container
  template:
    metadata:
      labels:
        app: postgres-auth-container
    spec:
      containers:
        - name: postgres-auth-container
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-credentials
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata-auth
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata-auth
          persistentVolumeClaim:
            claimName: postgres-auth-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
spec:
  selector:
    app: postgres-auth-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
